# .github/workflows/release_build.yml
name: Unified Release Build

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on pushes to tags like v1.0.0

jobs:
  build_macos:
    runs-on: macos-latest # Use the latest macos runner
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python
      with:
        python-version: '3.12.10' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install napari pyside6 torch ultralytics h5py natsort torchvision tqdm timm ml_collections pydicom scikit-image scipy bokeh matplotlib

    - name: Build with PyInstaller
      run: pyinstaller OCT_mac_app.spec

    - name: Zip macos executable
      run: |
        cd dist
        zip -r OCT_mac_app.zip OCT_mac_app.app
        ls -l
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # Action to upload the built executable as an artifact
      with:
        name: OCT_mac_app # Name of the artifact
        path: dist/OCT_mac_app.zip # Path to the zipped executable

  build_windows:
    runs-on: windows-latest # Use the latest Windows runner
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python
      with:
        python-version: '3.12.10' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install napari pyside6 torch ultralytics h5py natsort torchvision tqdm timm ml_collections pydicom scikit-image scipy bokeh matplotlib

    - name: Build with PyInstaller
      run: pyinstaller OCT_windows_app.spec

    - name: Zip Windows executable
      run: |
        tar -czvf OCT_windows_app.tar.gz -C dist OCT_windows_app.exe
        ls -l OCT_windows_app.tar.gz
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # Action to upload the built executable as an artifact
      with:
        name: OCT_windows_app # Name of the artifact
        path: dist/OCT_windows_app.tar.gz # Path to the zipped executabl

  create_release:
    runs-on: ubuntu-latest
    needs: [build_windows, build_macos] 
    permissions:
      contents: write 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: OCT_windows_app 
        path: ./release_assets/windows # Download to a specific subfolder

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: OCT_mac_app
        path: ./release_assets/macos # Download to a specific subfolder

    - name: List downloaded files (for debugging)
      run: ls -R ./release_assets

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./release_assets/windows/OCT_windows_app.tar.gz
          ./release_assets/macos/OCT_mac_app.zip
        name: Release ${{ github.ref_name }} # Unified release name
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
